// Firmware presets pushed into the embedded editor.
//
// The code does not live here. Each board is a PlatformIO project under
// firmware/ -- that is the tree that gets flashed to hardware -- and the browser
// gets firmware/build/<name>.ino, a single-file bundle of exactly those sources
// generated by `node tools/bundle.mjs`. What you read in the editor is what
// runs on the board, and the bundle is compiled and flown in the host test
// before it is ever served here.
//
// The recommended board is the ESP32 DevKit V1: it is the networked part in this
// build (Xtensa LX6 dual-core, WiFi+BT) and the one proven to compile and run
// under the container's emulation. Boards report their own state over serial,
// which is what the ranch reads back -- the scene mirrors the board, not the
// other way round.

export const BOARD = 'ESP32 DevKit V1';
// The inspection board is not the same module as the other four: the OV2640 needs the
// S3's DVP pin count, and its platformio env is esp32-s3-devkitc-1.
export const BOARD_S3 = 'ESP32-S3-DevKitC-1 + OV2640';
// What is actually bolted to the show airframe. `board` above is the string the
// simulator's own board list is matched against, so it stays what that list says; this
// is the line the drawer prints, and naming a camera on an aircraft that carries an RTK
// receiver instead would be a label the BOM contradicts.
export const SHOW_KIT = 'ESP32-S3-DevKitC-1 + NEO-M9N RTK + 2×WS2812B';

// What each pin is actually bolted to on the ranch, straight out of that board's
// board.h. The simulator's canvas is the same blink example for every preset -- one
// LED and a resistor -- so without this the panel would draw a light bulb no matter
// whether it was showing a fire loop or a three-phase current transformer.
//
// `sim: true` marks the one part the simulator really renders, so it can be drawn
// differently from the harness we are describing.
export const PRESETS = [
  {
    id: 'light', label: '照明控制板 · GPIO4/GPIO2 双路', board: BOARD, src: '/firmware/build/lighting.ino',
    wiring: [
      { p: 'GPIO4', k: 'out', d: '场院周界接触器', live: 'street', sim: true },
      { p: 'GPIO2', k: 'out', d: '门廊 / 厨房回路', live: 'house', sim: true },
      { p: 'GPIO27', k: 'out', d: '牛舍高棚 0-10 V 调光器' },
      { p: 'GPIO36', k: 'adc', d: '屋檐光照 LDR', live: 'lux' },
      { p: 'GPIO37', k: 'adc', d: '灯头母线电流互感器', live: 'amp' },
      { p: 'GPIO35', k: 'in', d: '牛舍人体红外' },
      { p: 'GPIO34', k: 'in', d: '驱动器故障干接点' },
      { p: 'GPIO21/22', k: 'bus', d: 'DS3231 时钟（断电后仍按天文时刻）' },
      { p: 'GPIO18', k: 'out', d: '外部看门狗喂狗' },
    ],
  },
  {
    id: 'drone', label: '无人机巡检板 · MAVLink 巡航 + MJPEG 图传', board: BOARD_S3, src: '/firmware/build/drone.ino',
    wiring: [
      { p: 'GPIO17/18', k: 'bus', d: '飞控 UART1 · MAVLink 2' },
      { p: 'GPIO3-16', k: 'bus', d: '摄像头 DVP 8bit + PWDN/RESET' },
      { p: 'GPIO38', k: 'out', d: '安全开关输出（高 = SAFE，锁死电机）' },
      { p: 'GPIO39', k: 'in', d: '钥匙 ARM 开关（低 = 闭合）' },
      { p: 'GPIO40', k: 'out', d: '外部看门狗喂狗' },
      { p: 'GPIO42', k: 'out', d: '蜂鸣器（失联/低电）' },
      { p: 'GPIO1', k: 'adc', d: '电池分压 · 电压', live: 'mv' },
      { p: 'GPIO2', k: 'adc', d: '电流互感器', live: 'amp' },
      { p: 'GPIO21/46/47/48', k: 'bus', d: 'SD 卡（照片与日志）' },
      { p: 'GPIO43/44', k: 'bus', d: '调试 UART · 遥测帧' },
    ],
  },
  {
    id: 'water', label: '水利控制板 · 牛舍定时 + 主屋独立', board: BOARD, src: '/firmware/build/water.ino',
    wiring: [
      { p: 'GPIO27', k: 'out', d: '牛舍电磁阀 24 V（MOSFET）', live: 'barn' },
      { p: 'GPIO26', k: 'out', d: '主屋电磁阀 24 V', live: 'house' },
      { p: 'GPIO25', k: 'out', d: '增压泵接触器', live: 'pump' },
      { p: 'GPIO4', k: 'in', d: '牛舍支路水表 7.5 Hz/L' },
      { p: 'GPIO13', k: 'in', d: '主屋支路水表 7.5 Hz/L' },
      { p: 'GPIO36', k: 'adc', d: '管路压力 0.5-4.5 V / 0-10 bar', live: 'press' },
      { p: 'GPIO37', k: 'adc', d: '水塔电阻式浮子', live: 'tank' },
      { p: 'GPIO35', k: 'in', d: '泵房漏水绳（湿 = 低）' },
      { p: 'GPIO34', k: 'in', d: '水塔满位（停补水，不溢流）' },
      { p: 'GPIO21/22', k: 'bus', d: 'DS3231 时钟（程序穿越断电）' },
      { p: 'GPIO18', k: 'out', d: '外部看门狗喂狗' },
      { p: 'GPIO2', k: 'out', d: '板载状态灯', sim: true },
    ],
  },
  {
    id: 'power', label: '配电监测板 · 三相计量 + 减载/漏电跳闸', board: BOARD, src: '/firmware/build/power.ino',
    wiring: [
      { p: 'GPIO36', k: 'adc', d: 'A 相电压 ZMPT101', live: 'va' },
      { p: 'GPIO37', k: 'adc', d: 'B 相电压 ZMPT101', live: 'vb' },
      { p: 'GPIO32', k: 'adc', d: 'C 相电压 ZMPT101', live: 'vc' },
      { p: 'GPIO33', k: 'adc', d: 'A 相电流互感器 15 mV/A', live: 'ia' },
      { p: 'GPIO34', k: 'adc', d: 'B 相电流互感器', live: 'ib' },
      { p: 'GPIO35', k: 'adc', d: 'C 相电流互感器', live: 'ic' },
      { p: 'GPIO21/22', k: 'bus', d: 'ADS1115（柜温 + 漏电流）+ DS3231' },
      { p: 'GPIO23', k: 'in', d: 'A 想过零比较器（频率只从这里来）' },
      { p: 'GPIO18', k: 'in', d: '主闸辅助干接点', live: 'brk' },
      { p: 'GPIO19', k: 'in', d: '水泵接触器辅助（证明真闭合）', live: 'pump' },
      { p: 'GPIO25', k: 'out', d: '水泵接触器线圈', live: 'pump' },
      { p: 'GPIO26', k: 'out', d: '场院照明馈线接触器', live: 'lit' },
      { p: 'GPIO0', k: 'in', d: '水泵回路 手/自动 许可' },
      { p: 'GPIO39', k: 'in', d: '照明回路 手/自动 许可' },
      { p: 'GPIO4', k: 'out', d: '窗口型看门狗喂狗' },
      { p: 'GPIO2', k: 'out', d: '板载状态灯', sim: true },
    ],
  },
  {
    id: 'fire', label: '消防监测板 · 四回路监督 + 跨回路确认 + 拨号', board: BOARD, src: '/firmware/build/fire.ino',
    wiring: [
      { p: 'GPIO37', k: 'adc', d: '主屋探测器回路 4k7 EOL', live: 'z0' },
      { p: 'GPIO36', k: 'adc', d: '牛舍探测器回路', live: 'z1' },
      { p: 'GPIO32', k: 'adc', d: '仓库 / 饲料间回路', live: 'z2' },
      { p: 'GPIO33', k: 'adc', d: '配电房回路（火最先来的地方）', live: 'z3' },
      { p: 'GPIO34', k: 'adc', d: '破玻璃手动报警按钮', live: 'mcp' },
      { p: 'GPIO35', k: 'adc', d: '湿式喷淋水流开关', live: 'flow' },
      { p: 'GPIO25', k: 'out', d: '室内警铃继电器 24 V', live: 'siren' },
      { p: 'GPIO27', k: 'out', d: '室外频闪', live: 'strb' },
      { p: 'GPIO14', k: 'out', d: '喷淋泵许可干接点', live: 'pump' },
      { p: 'GPIO26', k: 'in', d: '警铃衔铁辅助（证明响过）' },
      { p: 'GPIO5', k: 'in', d: '钥匙 自动 / BYPASS', live: 'arm' },
      { p: 'GPIO13', k: 'in', d: '静音按钮（ momentary）' },
      { p: 'GPIO18', k: 'in', d: '试铃按钮' },
      { p: 'GPIO21/22', k: 'bus', d: 'DS3231（日志要有时间）' },
      { p: 'GPIO4', k: 'out', d: '外部看门狗喂狗' },
      { p: 'GPIO2', k: 'out', d: '板载状态灯', sim: true },
    ],
  },
  {
    // One airframe of the show fleet. It is on the same S3 module as the inspection
    // board but wired for a different job: the RTK receiver is the thing that decides
    // whether the show can start at all, and the two pixels are the audience's view of
    // it. Every number here is a #define in firmware/show/src/board.h.
    id: 'show', label: '表演机 · RTK 定位 + 两颗 WS2812', board: BOARD_S3, kit: SHOW_KIT,
    src: '/firmware/build/show.ino',
    wiring: [
      { p: 'GPIO8', k: 'out', d: 'WS2812B 臂灯 + 腹部信标（满白 160 mA/颗）', live: 'led' },
      { p: 'GPIO16/15', k: 'bus', d: 'NEO-M9N RTK 模块 UART1 @115200（UBX NAV-PVT 5 Hz）', live: 'n' },
      { p: 'GPIO2', k: 'in', d: 'GNSS 秒脉冲 TIMEPULSE：全机群在同一秒起飞' },
      { p: 'GPIO17/18', k: 'bus', d: '飞控 MAVLink @57600（位置目标 + 心跳回读）' },
      { p: 'GPIO39', k: 'in', d: 'SAFE 钥匙开关（低 = 插入，电机锁死）' },
      { p: 'GPIO1', k: 'adc', d: '电池分压 4.3:1（4S）', live: 'batt' },
      { p: 'GPIO41', k: 'out', d: '有源蜂鸣器（失联 / 低电才响）' },
      { p: 'GPIO42', k: 'out', d: '台架灯：一闪等节目，两闪在飞' },
      { p: 'GPIO40', k: 'out', d: '外部看门狗喂狗（SGM823 类）' },
      { p: 'TX/RX 43/44', k: 'bus', d: 'USB-CDC 控制台：编排页的「上传节目」往这里敲 show=SHOWPLAN,…' },
    ],
  },
];

const cache = new Map();

// null means "use the example sketch that came with the board".
export async function presetCode(preset) {
  if (!preset || !preset.src) return null;
  if (cache.has(preset.src)) return cache.get(preset.src);
  const r = await fetch(preset.src, { cache: 'no-store' });
  if (!r.ok) throw new Error(`${preset.src} 取不到（HTTP ${r.status}），先运行 node tools/bundle.mjs`);
  const text = await r.text();
  cache.set(preset.src, text);
  return text;
}

/* ---------- serial telemetry parsing ---------- */
function fields(line, prefix) {
  const out = {};
  for (const part of line.slice(prefix.length).split(',')) {
    const i = part.indexOf('=');
    if (i > 0) out[part.slice(0, i)] = part.slice(i + 1);
  }
  return out;
}

// Newest "<PREFIX>,k=v,k=v" line in a serial transcript, or null.
export function lastTelemetryLine(text, prefix) {
  if (!text) return null;
  const lines = text.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i].trim();
    if (line.startsWith(prefix + ',') && line.includes('=')) return line;
  }
  return null;
}

// Its fields. The line itself is exported too because the panels count frames, and
// "the transcript grew" also counts the firmware's event lines.
export function parseTelemetry(text, prefix) {
  const line = lastTelemetryLine(text, prefix);
  return line ? fields(line, prefix) : null;
}
